export { default as Header } from './header/Header'
export { default as How } from './how/How'
export { default as Jobs } from './jobs/Jobs'
export { default as Slider } from './slider/Slider'
export { default as Contact } from './contact/Contact'
export { default as ContactP } from './contactPhone/ContactP'
export { default as Footer } from './footer/Footer'